language: c
sudo: required
branches:
  only:
  - master
before_install:
- mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20160619/texlive.tar.xz | tar -JxC $HOME/texlive
- PATH=$HOME/texlive/bin/x86_64-linux:$PATH
- sudo apt-get update -qq
- sudo apt-get install -y libboost-dev
install:
- tlmgr update --self
- tlmgr install epstopdf
- git clone https://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda_${TRAVIS_OS_NAME}.sh
- git clone https://github.com/wtbarnes/nbflow.git && cd nbflow && python setup.py install && cd ..
- git clone https://github.com/wtbarnes/EBTEL_analysis.git
- git clone https://github.com/rice-solar-physics/EBTEL_C.git && cd EBTEL_C/build && ./build && cd ../..
- git clone https://github.com/wtbarnes/EBTEL-2fluid_repo.git && cd EBTEL-2fluid_repo/build && ./build && cd ../..
- git clone https://github.com/rice-solar-physics/apolloDB
- git clone --recursive https://github.com/rice-solar-physics/IonPopSolver && scons && cd ..
before_script:
- scons
- cd site && make && cd ..
script:
- ghp-import -m "Building site" -b gh-pages site/output
- git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} gh-pages
env:
  global:
    - EXP_DIR=`pwd`
    - PYTHON_VERSION=2.7
    - NUMPY_VERSION='stable'
    - ASTROPY_VERSION='stable'
    - CONDA_DEPENDENCIES='ipython jupyter matplotlib pyyaml scons seaborn scipy'
    - PIP_DEPENDENCIES='ghp-import'
    - secure: "F5RTTtr4ystjF7KKKm/YOHVNaPkt0swt9JC8kALJba3L0nod5Ed4ARFEgotsyzO3/ztKRl0/8kGAs7stqFUJCwgaqz0O2600sSNa0NXLov63szAverJ2IXiYdbBMxZNc1jGkFbQ63v3VwRZvuv9Kv3vrZ1dbBcK0ZRB/JUrdHEb2f2ZYOuAl05pep0P+tlCMV6LZS8fYh2y7+nVsx4W/yy3QsX9E+yZhzhNNF/dTMc7AijJhD2tUnXYOzNUhKcEfijYiAewsRoMat+mxJxcI9IuYeJhe8cfP3Ar2ijm5Uz6hrxznFyDczhl3sAklCTJV5+zKGG80cSD8MuvRMFhWHUfmBJafNazXiG2oV6blkVMJi79P36iNuxRA/LCSENOQAdjvHQcJ2QLn1+wn35HGgjDsA0Z+++LSBFfPtp11+LnVDUO1WyLZryksLa11AVMQf1HZ0yekaZD83ONbEmQg8RktW5qFnTtgQ+wTBHDmUMeRRbr0s3xg/rUwKeVBxtdHlOkMV+HnU7Wp5xtbBNTHQ2ZqkI5et52Rq92+g/dCeyDwYAL1jbxQfesAq+Ij4DbZBPt1ul7LhzVH+Tt/PREOSvDHIp+xk/39jqIZ3AgGkcGKGW5wQCP3WHzFXeYzw8jVIKyVlbh2t+x7479i1MUNRi6RcNGXdbFRR9FLpE5/ha8="
