language: c
sudo: required
branches:
  only:
  - master
before_install:
- mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20160619/texlive.tar.xz | tar -JxC $HOME/texlive
- PATH=$HOME/texlive/bin/x86_64-linux:$PATH
- sudo apt-get update -qq
- sudo apt-get install -y libboost-dev
install:
- tlmgr update --self
- tlmgr install epstopdf
- git clone https://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda_${TRAVIS_OS_NAME}.sh
- git clone https://github.com/wtbarnes/nbflow.git && cd nbflow && python setup.py install && cd ..
- git clone https://github.com/wtbarnes/EBTEL_analysis.git
- git clone https://github.com/rice-solar-physics/EBTEL_C.git && cd EBTEL_C/build && ./build && cd ../..
- git clone https://github.com/wtbarnes/EBTEL-2fluid_repo.git && cd EBTEL-2fluid_repo/build && ./build && cd ../..
- git clone https://github.com/rice-solar-physics/apolloDB
- git clone --recursive https://github.com/rice-solar-physics/IonPopSolver && scons && cd ..
before_script:
- scons
- cd site && make && cd ..
script:
- ghp-import -m "Building site" -b gh-pages site/output
- git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} gh-pages
env:
  global:
    - EXP_DIR=`pwd`
    - PYTHON_VERSION=2.7
    - NUMPY_VERSION='stable'
    - ASTROPY_VERSION='stable'
    - CONDA_DEPENDENCIES='ipython jupyter matplotlib pyyaml scons seaborn scipy'
    - PIP_DEPENDENCIES='ghp-import'
    - secure:
